### ISSUE TITLE
Typo in distinguishability table (says bigint + bigint are distinguishable)

### ISSUE THREAD

**Issue by bathos** [whatwg/webidl#1010]
The [distinguishability table](https://heycam.github.io/webidl/#distinguishable-table) currently shows `(b)` at the bigint + bigint cell. I’m pretty sure this is a typo — it seems like it’s really supposed to be at numeric + bigint.

![Screenshot of the distinguishability matrix with a red arrow showing which cell the B is supposed to be in](https://user-images.githubusercontent.com/6257356/128647895-648574d4-17b0-4eb2-ba10-ed2485c31c66.png)

**Comment by TimothyGu** [comment]
Good catch!
