### ISSUE TITLE
Allow static operations to have the same name as regular operations

### ISSUE THREAD

**Issue by lucacasonato** [whatwg/webidl#1097]
WebIDL currently specifies that:

> The identifier of a static operation also must not be the same as the identifier of a regular operation defined on the same interface.

In light of https://github.com/whatwg/fetch/issues/1389, I'd like to remove this limitation. The limitation was originally added in https://github.com/whatwg/webidl/commit/082298c0f7e4d231d121823778f820f7d852ca55 by @heycam. Does anyone remember why?

Is anyone opposed to this change?

**Comment by annevk** [comment]
Nothing in https://lists.w3.org/Archives/Public/public-script-coord/2013OctDec/ looks relevant.

Is there precedent in JS? @codehag, do you know?

Overall though this seems fine to me. Static members are distinct enough to not cause confusion I think.

**Comment by codehag** [comment]
With regards to static methods sharing a name with an instance method of a builtin -- as far as I know, no. But for adding an options bag to an existing static method, I believe we have done that and we have definitely discussed doing it, for example for `map.emplace`, which could instead be `map.get(key[, options])`.

**Comment by yuki3** [comment]
I have a few concerns.

(1) Web IDL was originally (and hopefully have been) designed to be language-neutral (to support more language bindings than just an ECMAScript binding only).  ECMAScript is fine with this proposal, but what about other languages?  I understand that many people (or almost all people) think that it's unlikely that Web IDL will support other language bindings, but it's technically possible in the future, I think.  And some programming languages wouldn't be okay with this proposal.

(2) There are tons of JavaScript programming beginners.  Is this proposal helpful or rather confusing for those beginners?  Especially in raw JavaScript which is type-less, could this proposal be error-prone and/or making debugging harder?

I don't know very much about the background.  Why do we want this change in the first place?

By the way, thank you Domenic for notifying me on this topic.

**Comment by lucacasonato** [comment]
@annevk You mention Rust: https://crates.io/crates/web-sys would definitely have to deal with this change. Because of that, what are your thoughts on this @alexcrichton? Do you have ideas on how this could be dealt with in web-sys?

Regarding the trade-off, I agree that "potential implementation inconvenience" all the way at the bottom of the list. "most logical name" definitely goes first.

**Comment by yuki3** [comment]
Just in case that my point was misunderstood, my main concern is about the possibilities that in the future we will have "Java binding", "Rust binding", etc. in addition to [the currently-existing "ECMAScript binding" in Web IDL](https://webidl.spec.whatwg.org/#ecmascript-binding), rather than implementation languages.  The current Web IDL supports ECMAScript binding only, but we can have more language binding support in the future.

> Response.json() is for creation, responseInstance.json() is for reading.

To me, `Response.createJson` for example looks as much "logical" as `json` does.  There must be a lot of other names with the same amount of "logical".  I personally do not like taking a risk just for this naming nor being unfair to non-JS languages.

**Comment by yuki3** [comment]
Thanks for the comments.  Then, I have no objection.
