### ISSUE TITLE
Should 'undefined' be disallowed as an attribute type? 

### ISSUE THREAD

**Issue by marcoscaceres** [whatwg/webidl#1112]
Over on WebGPU, there is the following [IDL fragment](https://www.w3.org/TR/webgpu/#webgpu-interfaces) specified:

```WebIDL
interface mixin GPUObjectBase {
    attribute (USVString or undefined) label;
};
```

Leaving aside the issues with this `label` attribute itself, I'm wondering if we should outright ban `undefined` as an attribute type? 

I personally can't think of any strong reason for an attribute to be declared `undefined` (unless it was settable to `any`). But I might be missing something obvious. It would be extremely confusing if an attribute was present and yet `undefined` (instead of null or "", in the case above for instance).  

For the case above, Gecko, for instance, willfully violates the spec by null'ing the label attribute:
https://searchfox.org/mozilla-central/source/dom/webidl/WebGPU.webidl#51
 
A quick grep of WPT's IDLs and also Gecko's IDLs, I can't find any place in the Platform the where there is a `attribute undefined` specified or a union that is includes `undefined` for an attribute type. 

Thoughts?

**Comment by petervanderbeken** [comment]
> For the case above, Gecko, for instance, willfully violates the spec by null'ing the label attribute: https://searchfox.org/mozilla-central/source/dom/webidl/WebGPU.webidl#51

The patch for switching Gecko's WebIDL parser/codegen to undefined hasn't landed yet, so taking that example as any sign one way or the other isn't right.

**Comment by marcoscaceres** [comment]
ok, closing this for now.
