### ISSUE TITLE
DOMException needs Exposed=*

### ISSUE THREAD

**Issue by bathos** [whatwg/webidl#1136]
Currently DOMException’s exposure set is `(Window, Worker)`. However there are interfaces whose exposure sets are `*` which define operations that can throw DOMExceptions:

- [AbortController.prototype.abort](https://dom.spec.whatwg.org/#dom-abortcontroller-abort)
- [AbortSignal.abort](https://dom.spec.whatwg.org/#dom-abortsignal-abort)
- [AbortSignal.timeout](https://dom.spec.whatwg.org/#dom-abortsignal-timeout)
- [EventTarget.prototype.dispatchEvent](https://dom.spec.whatwg.org/#dom-eventtarget-dispatchevent)
- ...probably a bunch more

Likewise there are constructs found in global contexts not included in the `(Window, Worker)` exposure set with steps that specify throwing DOMExceptions, e.g. [PaintWorkletGlobalScope.prototype.registerPaint](https://drafts.css-houdini.org/css-paint-api/#dom-paintworkletglobalscope-registerpaint).

_Curious aside: I checked what Chromium’s current implementation of PaintWorkletGlobalScope does in practice and found that it did throw a DOMException there as advertised yet did not expose DOMException as a global. The surprise was that most interfaces that are allegedly universal weren’t present there, either, so it’s currently an odd little world where `ReadableStreamDefaultController` is at-the-ready but not, say, `URL`._

**Comment by annevk** [comment]
cc @Ms2ger @domenic

**Comment by Ms2ger** [comment]
Good point, oversight on my side. PRd as #1137.
