### ISSUE TITLE
pp-webidl fails on Review Drafts

### ISSUE THREAD

**Issue by annevk** [whatwg/webidl#1195]
We're running into a subtle issue with Review Drafts. This first surfaced in #1194 but also affects the prior RD. Due to various settings in Bikeshed the resulting HTML ends up differing slightly between LS and RD which causes the JS to trip.

The simplest of these is probably
```js
document.querySelector("div[data-fill-with=\"grammar-index\"]").innerHTML = wrap(output);
```
failing due to that `div` element no longer being present. This is happening to several other similar `div` elements as well, but those end up failing silently. The result though is that various grammar productions do not end up in the final copy of the standard.

@tabatkins do you know what could cause this? I looked a bit at `slimBuildArtifact` in Bikeshed and various other settings, but nothing really jumped out to me.

For debugging, you can compare:

* https://webidl.spec.whatwg.org/review-drafts/2022-03/
* https://webidl.spec.whatwg.org/commit-snapshots/e5afaf75c697ef14df26a2fe4557fb789ac60b49/

You can find the script at `<script class="remove">` in the source of the first one as it essentially failed server-side when generating the draft.

**Comment by domenic** [comment]
Makes sense; thanks for debugging for us, Tab! I think we should be able to find an alternate way of identifying the div we need to manipulate, even in the slim version... I can give it a try next week when I'm back from vacation.

**Comment by annevk** [comment]
Note that it's not a single `div` element. This is just the one that fails the most loudly. It does seem like we could replace these `data-*` attributes with non-`data-*` attributes (e.g., `idl-grammar` attributes) as the `data-fill-with` values are custom and not recognized by Bikeshed anyway, but we'd have to update the inline script as well as the `pp-webidl` library at https://github.com/tobie/webidl-grammar-post-processor. That would require @tobie's help.

**Comment by tobie** [comment]
LMK how I can help. I've also added a bunch of you to that repo to lower the bus factor.

**Comment by domenic** [comment]
I have a fix. Basically we'll just stop using `data-fill-with=""` and instead use a non-data attribute, `grammar-fill=""` or similar. And then strip them all out in post-processing to keep the document valid.

I'll work on a couple PRs.
