### ISSUE TITLE
Does requiring a dictionary type implicitly allow passing dictionaries that inherit from it?

### ISSUE THREAD

**Issue by rakuco** [whatwg/webidl#1199]
See w3c/sensors#439. The spec has an algorithm that takes a few parameters, and I'd like to change one of them from being just "a dictionary object" to being an instance of a specific dictionary type or any dictionary type inheriting from it.

My current attempt just says "a `FooBarBase` dictionary instance". Is that enough to cover the "and types inheriting from it" or do I need to be more explicit in the wording there?

**Comment by annevk** [comment]
Usually that suffices for a specification-level algorithm. At the IDL layer though you wouldn't be able to access members of inherited dictionaries if your IDL signature only takes the base dictionary.

**Comment by rakuco** [comment]
Thanks. At the spec level this algorithm only checks a key present in the base dictionary, but it does iterate over all keys via "[For each](https://infra.spec.whatwg.org/#map-iterate) key → value of options" to invoke other checks on them.

Does it mean that this iteration would only actually iterate over the keys present in the base dictionary?

**Comment by annevk** [comment]
That depends on whether this is a specification-level algorithm (no, as there would not be any conversion and there's no specification error either as the types match up) or IDL conversion from ES to IDL dictionary (yes).

**Comment by rakuco** [comment]
Thank you, Anne. I think my PR is fine, as the ES->IDL dictionary conversion happens beforehand (and the destination type is always one of the derived dictionaries).
