### ISSUE TITLE
PR changed the setlike `add` method to return the value that was added to the setlike object instead of the object itself. Was that an accident?

### ISSUE THREAD

**Issue by annevk** [whatwg/webidl#1268]
_Originally posted by @Liamolucko in https://github.com/whatwg/webidl/issues/1138#issuecomment-1408180279_

cc @tabatkins

**Comment by tabatkins** [comment]
I think it might have been an accident, yeah. I'll look into it.

**Comment by tabatkins** [comment]
Ok yup that was clearly a bug on my part. The old spec had add/delete defined in a combined algo, and branched on the operation to figure out what the return value is (the set for add, the value for delete). When I split them apart I must have mistakenly used the same code for each; I probably copy-pasted the algos.

I'll fix in a PR.
