### ISSUE TITLE
CreateMethodProperty removed from Ecma262

### ISSUE THREAD

**Issue by lukewarlow** [whatwg/webidl#1389]
### What is the issue with the Web IDL Standard?

WebIDL currently makes use of the `CreateMethodProperty` abstract-op from ECMAScript 262, however that's been removed recently ([PR](https://github.com/tc39/ecma262/pull/3279)), it seems [DefineMethodProperty](https://tc39.es/ecma262/#sec-definemethodproperty) is the function that replaces it.

**Comment by ljharb** [comment]
Thanks, filed #1391
