### ISSUE TITLE
Declaration of dictionaries with dynamic keys identified by type, but not by name

### ISSUE THREAD

**Issue by solomonkinard** [whatwg/webidl#1401]
### What problem are you trying to solve?

An IDL definition that would describe the following JavaScript:
```
{
  "1": "one",
  "1000000": million,
  "any": "wildcard"
}
```

### What solutions exist today?

Perhaps IDL supports an "object", and if so, that has no structure.

### How would you solve it?

Upon further investigation, it looks like this might already be possible through something like:
```
record<(DOMString or object), object> MyDynamicDictionary;
```

**Comment by domenic** [comment]
Can you be more specific about the web platform API specification you are trying to write?

**Comment by solomonkinard** [comment]
A concrete example would be a dictionary that could be a string or any arbitrary number, such as:
```
{
  "any": "any_icon.png",
  "128": "128_icon.png",
  "1024": "1024_icon.png",
}
```

**Comment by domenic** [comment]
Sorry, that isn't a web platform API specification...

**Comment by solomonkinard** [comment]
That was another concrete example of the problem to be solved.

**Comment by domenic** [comment]
Since Web IDL is a language for writing specifications for web platform features, and you don't seem to be writing one, let me close this.

**Comment by solomonkinard** [comment]
This issue was opened for the creation of the appropriate Web IDL to be used to solve the problem, as evidenced by the concrete examples provided. Is there a solution to the showcased problem already available in WebIDL, and if not, how would Web IDL look for solving it?
