### ISSUE TITLE
Callbacks in namepsaces?

### ISSUE THREAD

**Issue by tolmasky** [whatwg/webidl#1408]
### What is the issue with the Web IDL Standard?

Is there anywhere that explains why callbacks aren't allowed in namespaces? Would like to file a bug asking for it, but first want to make sure it isn't already explained why it is that way.

**Comment by domenic** [comment]
Callbacks don't correspond to JavaScript objects; they're helpers for making it easier for web specifications to call web developer code.

As such putting them in namespaces makes no sense, because there'd be no `namespaceObject.callbackObject`, since there is no `callbackObject`.

Hope this helps!
