### ISSUE TITLE
Should react to a Promise steps return a PromiseCapability instead of a Promise?

### ISSUE THREAD

**Issue by ADKaster** [whatwg/webidl#1443]
### What is the issue with the Web IDL Standard?

In https://webidl.spec.whatwg.org/#dfn-perform-steps-once-promise-is-settled the steps say:

> 6. Let newCapability be [?](https://tc39.es/ecma262/#sec-returnifabrupt-shorthands) [NewPromiseCapability](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-newpromisecapability)(constructor).
> Note: Not all callers will use the returned [Promise](https://webidl.spec.whatwg.org/#idl-promise). Implementations might wish to avoid creating newCapability in those cases.
> 7. Return [PerformPromiseThen](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-performpromisethen)(promise.[[Promise]], onFulfilled, onRejected, newCapability).

`PerformPromiseThen` will return `newCapability.[[Promise]]` when called this way, which results in the WebIDL algorithm returning a JS Promise object rather than a JS PromiseCapability object. Is this intentional?

I believe going off of https://webidl.spec.whatwg.org/#js-promise that the WebIDL algorithms should prefer to only expose the PromiseCapability to callers, and not the underlying [[Promise]] slot until converting back to JS at the WebIDL <-> JS Boundary.

I might rewrite the last step as

> 7.  [PerformPromiseThen](https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-performpromisethen)(promise.[[Promise]], onFulfilled, onRejected, newCapability).
> 8. Return newCapability.

cc @domenic

**Comment by domenic** [comment]
Yes, this fix looks good to me! A pull request would be appreciated.
