### ISSUE TITLE
Revamp ByteString, DOMString, and USVString

### ISSUE THREAD

**Issue by annevk** [whatwg/webidl#335]
I think the goal should be to map these to

* byte sequence
* JavaScript string
* scalar value string

as defined in the Infra Standard. We'll most likely need to copy at the boundary for ByteString, but for DOMString and USVString that depends on the resolution of https://github.com/whatwg/infra/issues/91. Unless we get more opinions there I suspect we'll end up copying for all three, because that's most in line with how things are done (I realize this is not a great argument).

https://heycam.github.io/webidl/#dfn-obtain-unicode can be removed and any usage of it can use https://infra.spec.whatwg.org/#javascript-string-convert instead.

Existing issues here that we should be sure to take into account: #84, #141, and #236.

**Comment by jyasskin** [comment]
I was talking to @domfarolino about this topic last week: I concluded that a USVString "is" a [scalar value string](https://infra.spec.whatwg.org/#scalar-value-string), so specs can use it as an Infra string without a conversion step.

**Comment by annevk** [comment]
I decided to close this based on @jyasskin's work in #1287 as the copy-at-boundary discussion is much larger. For now making it clear these are aliases seems sufficient.
