### ISSUE TITLE
[[DefineOwnProperty]] for legacy objects should not force configurability

### ISSUE THREAD

**Issue by bzbarsky** [whatwg/webidl#669]
https://heycam.github.io/webidl/#legacy-platform-object-defineownproperty step 3 says to set Desc.[[Configurable]] to true.  Why is that step there?  https://heycam.github.io/webidl/#dfn-named-property-visibility step 2 will ensure that own props defined on the object override named getter props, so it's not like the property will randomly go away or anything...

This testcase:
```
<!DOCTYPE HTML>
<script>
  Object.defineProperty(document, "foo",
                        { value: 5, configurable: false, writable: false });
  var attrs = document.documentElement.attributes;
  Object.defineProperty(attrs, "foo",
                        { value: 5, configurable: false, writable: false });
</script>
<img id="foo" name="foo">
<script>
  document.documentElement.setAttribute("foo", "test");  
  console.log(Object.getOwnPropertyDescriptor(document, "foo"));  
  console.log(Object.getOwnPropertyDescriptor(attrs, "foo"));  
</script>
```
shows that none of Firefox, Chrome, Safari implement this step 3, in either the overridebuiltins case or the non-overridebuiltins case.

@ms2ger @domenic @annevk

**Comment by Ms2ger** [comment]
This seems to have been added in June 2011: https://github.com/heycam/webidl/commit/9fb3b630

**Comment by bzbarsky** [comment]
Right, I believe that was before own properties always won over named ones in the named property visibility algorithm.
