### ISSUE TITLE
Incorrect rendering of decimal terminal as nonterminal in HTML

### ISSUE THREAD

**Issue by bathos** [whatwg/webidl#815]
![image](https://user-images.githubusercontent.com/6257356/66344606-49525780-e91c-11e9-8560-27e88a2a1744.png)

I believe the reason for this is that, even though the script that’s embedded in the def includes "decimal" [in its regex pattern](https://github.com/heycam/webidl/blob/8c71e7c7c8df10b6cecdbf164e89f43c96835faf/index.bs#L14671), this isn’t the script that’s [ultimately used to render the HTML](https://github.com/heycam/webidl/blob/8c71e7c7c8df10b6cecdbf164e89f43c96835faf/Makefile#L31-L35), which is [webidl-grammar-post-processor](https://github.com/tobie/webidl-grammar-post-processor). That package still has ‘float’ instead of ‘decimal’.

I’ve [opened a PR](https://github.com/tobie/webidl-grammar-post-processor/pull/1) which I think might fix the problem, but I’m opening the issue here because that repo has been inactive for two years.

**Comment by Ms2ger** [comment]
At the very least, we should import that code into this repo. I wouldn't mind seeing it rewritten in python either, but that's not urgent.
