### ISSUE TITLE
Editorial: align with HTML on calling ECMAScript JavaScript

### ISSUE THREAD

**Issue by annevk** [whatwg/webidl#863]
Currently there's some confusion already about this in the specification though the overwhelming majority still calls it ECMAScript. Aligning with HTML on JavaScript would make sense to me though.

**Comment by Buggie350** [comment]
[https://docs.couchdb.org/en/stable/intro/security.html?highlight=org%20couchdb%20users#authentication-database](CONTRIBUTING.md) ``

**Comment by jeremyroman** [comment]
Working on it.
