### ISSUE TITLE
How to return a SharedArrayBuffer object

### ISSUE THREAD

**Issue by annevk** [whatwg/webidl#865]
As far as I can tell a JS `SharedArrayBuffer` can enter IDL through an IDL `ArrayBuffer` that's effectively a pointer to the JS object.

Now assuming #342 is fixed and you can use `[AllowShared] ArrayBuffer` as return value, what language do you use to return a `SharedArrayBuffer`? Do you need to construct the JS object, then make an IDL `ArrayBuffer` object that points to it, and then return the IDL object?

**Comment by TimothyGu** [comment]
Since Web IDL never seems to say an IDL ArrayBuffer has to be an actual JavaScript ArrayBuffer, couldn't you just use `ArrayBuffer` as the return type in IDL? I.e., the [AllowShared] part in the return type isn't actually strictly necessary.

**Comment by domenic** [comment]
Sure, but how do you write spec prose saying that the IDL `ArrayBuffer` is actually a JavaScript SharedArrayBuffer? @annevk's last sentence points to one route, but it's kind of icky, as we'd like IDL to be an intermediary layer so that specs don't have to touch JS objects so directly.
