### ISSUE TITLE
What does FrozenArray mean in dictionaries?

### ISSUE THREAD

**Issue by saschanaz** [whatwg/webidl#900]
[Web Share](https://w3c.github.io/web-share/#sharedata-dictionary) has this dictionary:

```webidl
dictionary ShareData {
  FrozenArray<File> files;
  USVString title;
  USVString text;
  USVString url;
};
```

I guess it has nothing special as a dictionary member or as an argument. Should this be prevented to clarify things?

**Comment by annevk** [comment]
For an output dictionary it might make sense, but maybe it's best forbidden to align with attributes, indeed.

**Comment by domenic** [comment]
In general it would be good to align `FrozenArray<>` more with `ObservableArray<>`, in order to fix #810. See my previous plan in https://github.com/heycam/webidl/issues/810#issuecomment-538651524, which I think still holds and is more or less what I did for `ObservableArray<>`

**Comment by marcoscaceres** [comment]
Filed https://github.com/w3c/web-share/issues/165 for Web Share. Also came up in Payment Handler API https://github.com/w3c/payment-handler/pull/372 - I've not followed the ObservableArray discussion, but if we can recommend against people using FrozenArray as per the OP, that would be great (ban it outright, even better so tooling catch these and warn spec Editors).

**Comment by foolip** [comment]
I noticed a new case of this in https://github.com/web-platform-tests/wpt/pull/28739 and dug up all the current cases of `FrozenArray<T>` dictionary members:
https://immersive-web.github.io/hit-test/#idl-index
https://immersive-web.github.io/webxr/#idl-index
https://w3c.github.io/orientation-sensor/#idl-index
https://wicg.github.io/shape-detection-api/#idl-index
https://wicg.github.io/shape-detection-api/text.html#idl-index
https://wicg.github.io/ua-client-hints/#idl-index

It looks like in most cases it was just copy-pasted from an interface. While one can make sense of what this means and create the frozen arrays, it does seem kind of pointless. Whenever a dictionary is returned it's a new object, is there really any point in making arrays within frozen?

**Comment by foolip** [comment]
cc @yoavweiss since https://github.com/WICG/ua-client-hints/pull/228 is very recent, and any rationale might still be in memory :) Or was it just copypasta as it appears?

**Comment by amtunlimited** [comment]
@foolip WICG/ua-client-hints#228 was me, and yes it was just copypasta. I'll get it fixed soon-ish

**Comment by foolip** [comment]
Thanks for confirming @amtunlimited!

**Comment by domenic** [comment]
I think we should prohibit this, FWIW.

**Comment by domenic** [comment]
Let's roll this into https://github.com/whatwg/webidl/issues/900.
