### ISSUE TITLE
Consider adding `[LegacyASCIICaseInsentiveEnum]` for `element.insertAdjacent*` APIs

### ISSUE THREAD

**Issue by ExE-Boss** [whatwg/webidl#968]
The <code>[<var>element</var>.insertAdjacentElement](https://dom.spec.whatwg.org/#dom-element-insertadjacentelement)</code>, <code>[<var>element</var>.insertAdjacentText](https://dom.spec.whatwg.org/#dom-element-insertadjacenttext)</code> and <code>[<var>element</var>.insertAdjacentHTML](https://w3c.github.io/DOM-Parsing/#dom-element-insertadjacenthtml)</code> APIs take a <var>where</var>/<var>position</var> argument of <code>[DOMString](https://heycam.github.io/webidl/#idl-DOMString)</code> that is [ASCII lowercased](https://infra.spec.whatwg.org/#ascii-lowercase) and treated as if it were converted to the following enum:
```webidl
enum InsertPosition {
	"beforebegin",
	"afterbegin",

	"beforeend",
	"afterend"
};
```

Except that instead of throwing a <code>[TypeError](https://heycam.github.io/webidl/#exceptiondef-typeerror)</code> or a <code>[RangeError](https://heycam.github.io/webidl/#exceptiondef-rangeerror)</code><sup> <https://github.com/heycam/webidl/issues/489></sup>, a "<code>[SyntaxError](https://heycam.github.io/webidl/#syntaxerror)</code>" <code>[DOMException](https://heycam.github.io/webidl/#idl-DOMException)</code> is thrown instead.

## See also:
- <https://github.com/heycam/webidl/issues/489>
- <https://github.com/heycam/webidl/issues/491>
- <https://github.com/heycam/webidl/issues/893>

**Comment by annevk** [comment]
I think there should be more precedent before we standardize upon a pattern in IDL. Unless there's a reason handling it prose is difficult, but that does not appear to be the case here?
